import type { Metadata } from "next";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "../components/SessionProvider";

import { AuthButton } from "../components/AuthButton";
import { AppRoute, Navigation } from "@/components/Navigation";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/ThemeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <body className="bg-gradient-to-b from-zinc-100 to-zinc-200 dark:to-zinc-950 dark:from-zinc-900 h-screen w-screen">
            <header className="flex w-full justify-between items-center gap-2">
              <Navigation routes={AppRoutes} />
              <div className="flex gap-2">
                <AuthButton />
                <ThemeToggle />
              </div>
            </header>
            <main className="px-4 lg:px-16">{children}</main>
          </body>
        </ThemeProvider>
      </SessionProvider>
    </html>
  );
}

const AppRoutes: AppRoute[] = [
  {
    path: "/",
    name: "Home",
  },
  {
    path: "/auth",
    name: "NextAuth with SSR",
  },
  {
    path: "/links",
    name: "Form Requests with SSR",
  },
  {
    path: "/quiz",
    name: "Quiz 'Trello' Board",
  },
];
