import type { Metadata } from "next";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "../components/SessionProvider";

import { AuthButton } from "../components/AuthButton";
import { AppRoute, Navigation } from "@/components/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-neutral-900 to-neutral-800 h-screen w-screen">
        <SessionProvider session={session}>
          <main className="px-4 lg:px-16">
            <div className="flex w-full justify-between">
              <Navigation routes={AppRoutes} />
              <AuthButton />
            </div>
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}

const AppRoutes: AppRoute[] = [
  {
    path: "/",
    name: "Home",
  },
  {
    path: "/auth",
    name: "NextAuth with SSR",
  },
  {
    path: "/links",
    name: "Form Requests with SSR",
  },
];
