import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";

import { AuthButton } from "./components/AuthButton";
import { NavMenu, NextAuthRoutes } from "./components/NavMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <main className="px-4 lg:px-16">
            <AuthButton />
            <NavMenu routes={NextAuthRoutes} />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
